apiVersion: apps/v1
kind: Deployment
metadata:
  name: atrial-fibrillation-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: atrial-fibrillation-api
  template:
    metadata:
      labels:
        app: atrial-fibrillation-api
    spec:
      containers:
      - name: atrial-fibrillation-api
        image: tabed23/atrial-fibrillation-api:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: data-volume
          mountPath: /data
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
      volumes:
      - name: data-volume
        emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
